spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=formdb;encrypt=true;trustServerCertificate=true
    username: sa
    password: P@ssw0rd!Strong
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        default_schema: form_system
        format_sql: true

